// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozfbdtpucwlmhmpivvku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96ZmJkdHB1Y3dsbWhtcGl2dmt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzEwNDAsImV4cCI6MjA2MDY0NzA0MH0.WhhYyOw8AebVc8qMWhQ1GNP7l5mU3uUK97TqRut6ANs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);